language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t phoebelord/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phoebelord/react-test npm test

after_success:
# BUILD
  - docker build -t phoebelord/multi-client ./client
  - docker build -t phoebelord/multi-nginx ./nginx
  - docker build -t phoebelord/multi-server ./server
  - docker build -t phoebelord/multi-worker ./worker
# LOGIN
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
# PUSH
  - docker push phoebelord/multi-client
  - docker push phoebelord/multi-nginx
  - docker push phoebelord/multi-server
  - docker push phoebelord/multi-worker